### PR TITLE
src/CMakelists.txt: do not use wildcards for dependencies

### PR DESCRIPTION
**Pull request by abderrahim**
This is discouraged by cmake's documentation and doesn't work with the ninja generator.

### CODE REVIEW

**Comment by adhawkins** [comment]
Can you point to the place in CMake's documentation where this is discouraged?

**Comment by abderrahim** [comment]
[This](https://cmake.org/cmake/help/latest/command/aux_source_directory.html) is what I meant. What is actually discouraged is not listing all source files, perhaps this could use better wording?

**Comment by adhawkins** [comment]
Ok. So what is the issue with the ninja generator you mention then? I'm trying to work out if this change is strictly necessary, otherwise we end up with a situation in the future where a new .inc file is added, but the dependencies aren't correctly handled.

**Comment by abderrahim** [comment]
CMake passes the writes the contents of the DEPENDS as is to ninja, which can't find the "*.inc" file. (ninja doesn't support wildcards by design)

**Pull request merged**
